### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by MostHated** [velik97/EventBus#1]
Hey there,
    Any chance you could throw up a license file for this? Seems like a really neat package, but I am always apprehensive to use anything unless it has a proper license file on the repo.

Thanks!
-MH

**Comment by velik97** [comment]
Sory for waiting.
I've added WTFPL

**Comment by velik97** [comment]
Sory for waiting
I've added WTFPL

**Comment by MostHated** [comment]
Good deal, appreciated. :+1:
